import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url)), out = path.join(root, 'test-results');
await fs.mkdir(out, { recursive: true });
const html = await fs.readFile(path.join(root, 'dist/index.html'));
const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const address = `http://127.0.0.1:${server.address().port}/`;
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const checks = [], errors = [];
const record = (name, details = '') => { checks.push({ name, details }); console.log('PASS', name, details); };
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, acceptDownloads: true, isMobile: true, hasTouch: true });
const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
const fixtures = await page.evaluate(() => {
  const dimensions = [[900, 1200], [800, 1200], [900, 1200], [1400, 900], [1300, 900], [1000, 1000], [1400, 900], [900, 1300], [1100, 900]];
  return dimensions.map(([width, height], i) => {
    const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const c = canvas.getContext('2d');
    c.fillStyle = ['#bed2c1', '#ceb2a0', '#99b6ba', '#c0bc99'][i % 4]; c.fillRect(0, 0, width, height);
    c.fillStyle = '#2d5147'; c.beginPath(); c.moveTo(0, height * .7); c.lineTo(width * .4, height * .33); c.lineTo(width * .7, height * .68); c.lineTo(width, height * .42); c.lineTo(width, height); c.lineTo(0, height); c.fill();
    c.fillStyle = '#f7c47f'; c.beginPath(); c.arc(width * .6, height * .3, width * .12, 0, Math.PI * 2); c.fill();
    c.fillStyle = '#f6f0dd'; c.fillRect(width * .34, height * .58, width * .32, height * .32);
    c.fillStyle = '#f3e8d7'; c.font = `bold ${width * .09}px sans-serif`; c.fillText(String(i + 1).padStart(2, '0'), width * .08, height * .15);
    c.strokeStyle = '#cc6847'; c.lineWidth = width * .018; c.strokeRect(width * .03, height * .03, width * .94, height * .94);
    return canvas.toDataURL('image/png').split(',')[1];
  });
});
const paths = await Promise.all(fixtures.map(async (data, i) => { const target = path.join(out, `fixture-${i + 1}.png`); await fs.writeFile(target, Buffer.from(data, 'base64')); return target; }));
const story = '周末，我们去看山，也在城里散步。朋友分享沿途照片，还有以前的生活记录。这些照片放在一起，记下这次出行。';

try {
  await page.goto(address); await page.locator('#files').setInputFiles(paths);
  await page.waitForFunction(() => document.querySelector('#make').disabled === false);
  assert.equal(await page.locator('.photo-card').count(), 9);
  await page.locator('#title').fill('山间，和日常'); await page.locator('#story').fill(story);
  record('9 张照片按宽高比排布，中文表单可用');
  const original = await page.locator('.photo-open img').first().getAttribute('src');
  await page.locator('.photo-open').first().click(); await page.locator('cropper-image').waitFor();
  await page.locator('#crop-ratio').selectOption('1'); await page.locator('#crop-rotate').click(); await page.locator('#brightness').fill('108');
  await page.locator('#apply-crop').click(); await page.locator('#crop-dialog').waitFor({ state: 'hidden' });
  const cropped = await page.locator('.photo-open img').first().getAttribute('src'); assert.notEqual(cropped, original);
  await page.locator('.photo-open').first().click(); await page.locator('#crop-reset').click(); await page.locator('#crop-dialog').waitFor({ state: 'hidden' });
  assert.ok(await page.locator('.photo-open img').first().getAttribute('src') === original, '原图恢复后缩略图应保持一致');
  record('Cropper 比例裁剪、旋转、调色及原图恢复');
  await page.locator('#make').click(); await page.waitForTimeout(300);
  assert.equal((await page.locator('#book .page-body').allTextContents()).join(''), story);
  assert.equal(await page.locator('.stf__wrapper.--portrait').count(), 1);
  await page.locator('#next').click(); await page.waitForTimeout(650);
  const pair = page.locator('.pair[aria-hidden=false]'); assert.equal(await pair.count(), 1);
  const bounds = await pair.evaluate(node => { const area = node.querySelector('.photo-area').getBoundingClientRect(); return [...node.querySelectorAll('figure')].map(f => { const r = f.getBoundingClientRect(); return { width: r.width, height: r.height, ratio: r.width / area.width, margin: getComputedStyle(f).margin }; }); });
  bounds.forEach(b => { assert.ok(b.width > 115, JSON.stringify(b)); assert.equal(b.margin, '0px'); assert.ok(b.ratio > .45); });
  await page.waitForTimeout(2400); await page.screenshot({ path: path.join(out, 'phone-390.png'), fullPage: true });
  record('390px 手机单页；双人照片宽度充足，无默认边距挤压', JSON.stringify(bounds));
  await page.locator('#edit').click(); await page.locator('#edit-body').fill('我们分享生活，也把这一程记了下来。'); await page.locator('#edit-caption').fill('山间与街角 · 周末'); await page.locator('#apply-text').click();
  assert.ok(await page.locator('.pair[aria-hidden=false] .page-body').innerText() === '我们分享生活，也把这一程记了下来。');
  await page.waitForFunction(() => document.querySelector('#draft-status').textContent === '草稿已保存在本机');
  await page.reload(); await page.locator('#resume-banner').waitFor({ state: 'visible' }); await page.locator('#resume').click();
  await page.waitForTimeout(300); assert.ok((await page.locator('.pair .page-body').innerText()).includes('我们分享生活'));
  record('文字和图注编辑、本地草稿刷新后恢复');
  const beforeSwipe = await page.locator('#meter').innerText();
  await page.evaluate(() => {
    const target = document.querySelector('.stf__block'), r = target.getBoundingClientRect();
    const makeTouch = x => new Touch({ identifier: 1, target, clientX: x, clientY: r.y + r.height * .45 });
    const start = makeTouch(r.x + r.width * .8), end = makeTouch(r.x + r.width * .25);
    target.dispatchEvent(new TouchEvent('touchstart', { bubbles: true, cancelable: true, changedTouches: [start], touches: [start] }));
    target.dispatchEvent(new TouchEvent('touchmove', { bubbles: true, cancelable: true, changedTouches: [end], touches: [end] }));
    target.dispatchEvent(new TouchEvent('touchend', { bubbles: true, cancelable: true, changedTouches: [end], touches: [] }));
  });
  await page.waitForTimeout(650); assert.notEqual(await page.locator('#meter').innerText(), beforeSwipe); await page.locator('#prev').click(); await page.waitForTimeout(650);
  record('手机触屏滑动可完成翻页');
  await page.setViewportSize({ width: 320, height: 640 }); await page.waitForTimeout(250);
  const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth); assert.ok(horizontalOverflow <= 1, horizontalOverflow);
  const bookRect = await page.locator('#book-host').boundingBox(); assert.ok(bookRect.x >= 0 && bookRect.x + bookRect.width <= 321 && bookRect.y + bookRect.height <= 590, JSON.stringify(bookRect));
  record('320px 小屏无横向溢出，翻页和操作栏可见');
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200);
  await page.locator('.reader-menu summary').click();
  const downloadPromise = page.waitForEvent('download'); await page.locator('#download').click(); const download = await downloadPromise; const saved = path.join(out, 'offline-edition.html'); await download.saveAs(saved);
  const offline = await context.newPage(), requests = []; offline.on('pageerror', e => errors.push(e.message)); offline.on('request', request => { if (/^https?:/.test(request.url())) requests.push(request.url()); });
  await offline.goto(pathToFileURL(saved).href); await offline.waitForTimeout(350);
  assert.equal(await offline.locator('#reader').isVisible(), true); assert.equal(requests.length, 0); assert.ok((await offline.locator('.page-body').first().innerText()).includes('我们分享生活'));
  await offline.locator('#edit').click(); await offline.locator('#edit-caption').fill('离线也可以编辑'); await offline.locator('#apply-text').click();
  record('独立 HTML 离线打开、翻页与文字编辑，无 CDN 请求');
  await page.emulateMedia({ media: 'print' }); await page.evaluate(() => dispatchEvent(new Event('beforeprint')));
  const printable = await page.locator('#print-pages .magazine-page').count(), total = await page.locator('#book .magazine-page').count(); assert.equal(printable, total);
  await page.pdf({ path: path.join(out, 'sample-edition.pdf'), preferCSSPageSize: true, printBackground: true });
  const pdf = await fs.readFile(path.join(out, 'sample-edition.pdf')); const pdfPages = (pdf.toString('latin1').match(/\/Type\s*\/Page\b/g) || []).length; assert.equal(pdfPages, total);
  await page.evaluate(() => dispatchEvent(new Event('afterprint'))); await page.emulateMedia({ media: 'screen' });
  record('PDF 包含整本所有页面', `${pdfPages} 页`);
  const longBody = '这段文字来自用户编辑，打印时要完整保留。'.repeat(25);
  await offline.locator('#edit').click(); await offline.locator('#edit-body').fill(longBody); await offline.locator('#apply-text').click();
  await offline.emulateMedia({ media: 'print' }); await offline.evaluate(() => dispatchEvent(new Event('beforeprint')));
  assert.ok((await offline.locator('#print-pages .page-body').allTextContents()).join('').includes(longBody));
  const printBounds = await offline.locator('#print-pages .page-body').evaluateAll(nodes => nodes.map(n => { const b = n.getBoundingClientRect(), p = n.closest('.page-shell').getBoundingClientRect(); return b.bottom <= p.bottom - 15; })); assert.ok(printBounds.every(Boolean));
  record('长篇编辑正文在 PDF 中自动续页，保留全文');
  const desktopContext = await browser.newContext({ viewport: { width: 1280, height: 900 } }); const desktop = await desktopContext.newPage(); desktop.on('pageerror', error => errors.push(error.message));
  await desktop.goto(pathToFileURL(saved).href); await desktop.waitForTimeout(350);
  assert.equal(await desktop.locator('.stf__wrapper.--landscape').count(), 1);
  const initial = await desktop.locator('#meter').innerText(), rect = await desktop.locator('#book-host').boundingBox();
  await desktop.mouse.move(rect.x + rect.width - 4, rect.y + rect.height - 5); await desktop.mouse.down(); await desktop.mouse.move(rect.x + rect.width * .15, rect.y + rect.height * .8, { steps: 15 });
  const folding = await desktop.locator('.stf__item').evaluateAll(nodes => nodes.some(n => getComputedStyle(n).transform !== 'none'));
  await desktop.mouse.up(); await desktop.waitForTimeout(700); assert.notEqual(await desktop.locator('#meter').innerText(), initial); assert.ok(folding);
  await desktop.screenshot({ path: path.join(out, 'desktop-1280.png'), fullPage: true });
  await desktop.keyboard.press('ArrowLeft'); await desktop.waitForTimeout(650); assert.equal(await desktop.locator('#meter').innerText(), initial);
  await desktop.mouse.move(rect.x + rect.width - 4, rect.y + rect.height - 5); await desktop.mouse.down(); await desktop.mouse.move(rect.x + rect.width * .92, rect.y + rect.height * .95, { steps: 6 }); await desktop.mouse.up(); await desktop.waitForTimeout(650); assert.equal(await desktop.locator('#meter').innerText(), initial);
  record('电脑双页、页角拖拽完成或取消、方向键翻页');
  const palette = await desktop.evaluate(() => ['paper', 'ink', 'accent'].map(key => getComputedStyle(document.documentElement).getPropertyValue('--' + key).trim()));
  assert.notEqual(palette[2], '#9e4434'); record('Color Thief 照片配色已实际应用', palette.join(' / '));
  const limitPage = await desktopContext.newPage(); limitPage.on('pageerror', e => errors.push(e.message)); await limitPage.goto(address); await limitPage.locator('#files').setInputFiles(Array.from({ length: 21 }, (_, i) => paths[i % paths.length])); await limitPage.waitForFunction(() => document.querySelector('#make').disabled === false);
  assert.equal(await limitPage.locator('.photo-card').count(), 20);
  await limitPage.locator('#simplify').click(); assert.ok((await limitPage.locator('input[type=checkbox]:checked').count()) < 20);
  const firstId = await limitPage.locator('.photo-card').first().getAttribute('data-photo-id'); await limitPage.getByRole('button', { name: '后移照片 1', exact: true }).click(); assert.equal(await limitPage.locator('.photo-card').nth(1).getAttribute('data-photo-id'), firstId);
  record('最多 20 张、精简相似照片、按钮调整顺序');
  const legacyContext = await browser.newContext({ viewport: { width: 390, height: 844 } }), legacyPage = await legacyContext.newPage(); legacyPage.on('pageerror', e => errors.push(e.message)); await legacyPage.goto(address);
  const legacyPhoto = await desktop.locator('#edition-data').evaluate(node => JSON.parse(node.textContent).photos[0]);
  await legacyPage.evaluate(p => localStorage.setItem('photo-edition-draft', JSON.stringify({ title: '旧版草稿', style: 'daily', photos: [{ ...p, alt: '旧照片' }], pages: [{ layout: 'cover', title: '旧版草稿', body: '旧文字也完整保留。', photos: [p.id] }] })), legacyPhoto);
  await legacyPage.reload(); await legacyPage.locator('#resume-banner').waitFor({ state: 'visible' }); await legacyPage.locator('#resume').click(); assert.equal(await legacyPage.locator('#brand-title').innerText(), '旧版草稿'); assert.equal(await legacyPage.locator('.page-body').innerText(), '旧文字也完整保留。');
  record('旧版保存的照片和文字可迁移恢复');
  assert.deepEqual(errors, []); record('整个检查无 JavaScript 错误');
  await fs.writeFile(path.join(out, 'verification.json'), JSON.stringify({ passed: true, checks, errors, generatedAt: new Date().toISOString() }, null, 2));
} catch (error) {
  await page.screenshot({ path: path.join(out, 'failure.png'), fullPage: true }).catch(() => {});
  await fs.writeFile(path.join(out, 'verification.json'), JSON.stringify({ passed: false, checks, errors, failure: String(error), stack: error.stack }, null, 2)); throw error;
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
